### ISSUE TITLE
Discussion: Why pyo3_ffi vs pyo3

### ISSUE THREAD

**Issue by Dr-Emann** [ariebovenberg/whenever#148]
Just wondering what the reasoning is for using the lower level (and much more unsafe) pyo3_ffi bindings directly rather than the nicer pyo3 wrapper on top?

**Comment by ariebovenberg** [comment]
An updated benchmark on `__eq__`:


```
$ python -m timeit -s "from datetime import datetime, UTC; d1 = datetime.now(); d2 = datetime.now()" "d1 == d2"
20000000 loops, best of 5: 11.1 nsec per loop
$ python -m timeit -s "from whenever import Instant; d1 = Instant.now(); d2 = Instant.now()" "d1 == d2"
20000000 loops, best of 5: 11.5 nsec per loop
```

using this PyO3 definition added to the example `maturin_starter`:

```rust
    pub fn __richcmp__(&self, value: &Bound<'_, PyAny>, _x: pyo3::basic::CompareOp) -> bool {
        true
    }

```

(note: I did remember to build in `--release` mode)


```
$ python -m timeit -s "from maturin_starter.submodule import SubmoduleClass; f = SubmoduleClass(); f2 = SubmoduleClass()" "f == f2"
20000000 loops, best of 5: 17.7 nsec per loop
```

This looks a lot better, but note that this is the performance *without* the actual implementation. We'd still need to add the type checking and comparing the actual value. It's better than the 40ns observed in earlier PyO3 versions though. Could be worth doing a benchmark on the full logic 🤔

**Comment by ariebovenberg** [comment]
@Dr-Emann I've added this to the FAQ. PyO3/ffi discussion can always be opened later as PyO3 evolves further.
