### ISSUE TITLE
the time is wrong

### ISSUE THREAD

**Issue by BMaxV** [ariebovenberg/whenever#153]
Hey, I saw your reddit post.

Your time is wrong.

```
from whenever import Instant

import datetime

now = Instant.now()

print(now.format_common_iso())
print(datetime.datetime.now().isoformat())
```
```
2024-07-10T15:13:44.653539569Z
2024-07-10T17:13:44.653566
```

Datetime gets it right.

**Comment by ariebovenberg** [comment]
Hi @BMaxV thanks for posting. The difference you're seeing is that `Instant.now()` is in UTC—as indicated by the `Z` suffix. The `datetime.now()` is in your local timezone.

to get the 'correct' local time, explicitly do:

```python
now = Instant.now()
print(now.to_system_tz().format_common_iso())
```

**Comment by BMaxV** [comment]
Alright, thanks for the quick reply! That's a bit unintuitive, but if the library is better overall...

**Comment by ariebovenberg** [comment]
> That's a bit unintuitive

Coming from `datetime`, I can understand it takes some getting used to. `Instant` is explicitly independent of any local time representation. You find this in the major modern datetime libraries as well.

If it helps: use `SystemDateTime` if you're explicitly working in the system timezone.

```python
SystemDateTime.now()
# same as
Instant.now().to_system_tz()
```

**Comment by spacemanspiff2007** [comment]
> That's a bit unintuitive

I've found it to be the opposite. The docs explain the concept rather well ...
