### ISSUE TITLE
Windows access violation with Instant.from_utc()

### ISSUE THREAD

**Issue by ArneBachmannDLR** [ariebovenberg/whenever#167]
Trying to call Instant twice in a row hard-crashes the interpreter. I created a fresh conda environment and got this result:

```
(adb) D:\forks\IT\assetdb>python
Python 3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:27:10) [MSC v.1938 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

>>> from whenever import Instant
>>> Instant.from_utc(1970, 1, 1)
Instant(1970-01-01 00:00:00Z)
>>> Instant.from_utc(1970, 1, 1)
Windows fatal exception: access violation

Current thread 0x0000527c (most recent call first):
  File "<stdin>", line 1 in <module>
```

I was initially assuming that my date computation was before 1.1.1970 leading to a negative unix timestamp + crash, but in this case there must be something else.

**Comment by ariebovenberg** [comment]
Thanks for posting! Looks like it's something else indeed.I'll have a look

**Comment by ariebovenberg** [comment]
It shouldn't have anything to do with the system time settings BTW, `from_utc` is just a simple object instantiation. Looks like the problem may be incorrect object deallocation, which can be tricky to reproduce.

In any case I wasn't so lucky to be able to reproduce, even on a matching conda/python/windows environment:

```powershell
 PS C:\Users\acbov> python
Python 3.11.9 | packaged by Anaconda, Inc. | (main, Apr 19 2024, 16:40:41) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from whenever import Instant
>>> Instant.from_utc(1970, 1, 1)
Instant(1970-01-01 00:00:00Z)
>>> Instant.from_utc(1970, 1, 1)
```

Do you get the same problem with other values? Or other classes (e.g. `Time(0)`)?

**Comment by ArneBachmannDLR** [comment]
So weird...
```
>>> from whenever import Time
>>> Time(0)
Time(00:00:00)
>>> Time(0)
Windows fatal exception: access violation

Current thread 0x00005a6c (most recent call first):
  File "<stdin>", line 1 in <module>
```

**Comment by ariebovenberg** [comment]
Hmmm. What if you do:

```
>>> Time(0)
>>> object()  # clears the reference to the previous object
```

That at least narrows the problem down to deallocation

**Comment by ArneBachmannDLR** [comment]
```
>>> Time(0)
Time(00:00:00)
>>> object()
Windows fatal exception: access violation
```

**Comment by ariebovenberg** [comment]
Ok I have an idea. Can you try the `0.6.8rc1` release of `whenever`? It should be out once [this workflow](https://github.com/ariebovenberg/whenever/actions/runs/10716482095) completes

**Comment by ArneBachmannDLR** [comment]
Seems to work!
```
>>> fastuuid.uuid4()
UUID('a66b265a-8901-4e8c-a72e-9ec0a08a66bd')
>>> object()
<object object at 0x000001FE46156920>

>>> from whenever import Time
>>> Time(0)
Time(00:00:00)
>>> Time(0)
Time(00:00:00)
>>> Time(0)
Time(00:00:00)
>>> from whenever import Instant
>>> Instant.from_utc(1970,1,1)
Instant(1970-01-01 00:00:00Z)
>>> Instant.from_utc(1970,1,1)
Instant(1970-01-01 00:00:00Z)
```

**Comment by ariebovenberg** [comment]
Excellent. A propert release (0.6.8) should be out once [this workflow](https://github.com/ariebovenberg/whenever/actions/runs/10716722202) finishes.

**Comment by ArneBachmannDLR** [comment]
That's amazing! Was already able to continue the refactoring to the latest version which doesn't use `_AwareDateTime` anymore and replaced it with `Instant`

**Comment by ariebovenberg** [comment]
Happy to hear it. Thanks for taking the time to post 👍
