### ISSUE TITLE
Improved autocomplete

### ISSUE THREAD

**Issue by ariebovenberg** [ariebovenberg/whenever#176]
When developing the library, I tested the major editors (Neovim, VSCode, PyCharm) to ensure that autocomplete worked. However, as commented [here](https://github.com/ariebovenberg/whenever/issues/173#issuecomment-2417186703), some development environments don't pick the signatures of extensions correctly. Perhaps [this](https://github.com/ipython/ipython/issues/10044) is related.

Concrete steps to be made:
- [x] add `__text_signature__` to methods in Rust extension
- [x] eliminate `Disambiguation` alias so the literals are shown directly

**Comment by spacemanspiff2007** [comment]
I have complained prematurely: PyCharm does show the type hint only when entering the parameter.
Maybe the behavior was changed or it was always this way but I somehow missed it.
So imho the disambiguation is fine.

![grafik](https://github.com/user-attachments/assets/aabe6998-46ab-4760-ab43-fe21074e0d82)
![grafik](https://github.com/user-attachments/assets/3c762b57-27c4-46f3-85e7-778d73303843)

**Comment by ariebovenberg** [comment]
Good to hear PyCharm doesn't suffer from this issue. To be safe though, I'll still remove the alias since other editors/checkers may not.

**Comment by ariebovenberg** [comment]
The next release should significantly improve autocomplete for IDEs at least. There are more and better docstrings, and they link to the docs where needed

**Comment by ariebovenberg** [comment]
text signature has been properly configured in the latest release. One lingering issue is docstrings in the extension, which will get a separate issue
