### ISSUE TITLE
Docs: Add link do disambiguate table

### ISSUE THREAD

**Issue by spacemanspiff2007** [ariebovenberg/whenever#178]
Currently there are many places in the docs where the disambiguate parameter is described.
It would be very helpful if there was a direct link to this table so one can look up the meanings of the parameters quickly:
https://whenever.readthedocs.io/en/latest/overview.html#ambiguity-in-timezones

E.g. a link in the description of https://whenever.readthedocs.io/en/latest/api.html#whenever.LocalDateTime.assume_tz
If that's not possible a section on the left under changelog would also be fine.

**Comment by ariebovenberg** [comment]
@spacemanspiff2007 agree, that would be a good idea. I can include it in the next release—along with some other documentation improvements

**Comment by ariebovenberg** [comment]
The next release should make an improvement in this regard

before:

<img width="687" alt="image" src="https://github.com/user-attachments/assets/702199df-4993-48a3-a586-5bce0e303021">


after:

<img width="681" alt="image" src="https://github.com/user-attachments/assets/d358a8dc-0942-4984-8ab2-bdab7fa9a42f">

@spacemanspiff2007 what do you think?

**Comment by ariebovenberg** [comment]
release 0.6.10 is out with these improvements
