### ISSUE TITLE
Full docstrings in Rust extension

### ISSUE THREAD

**Issue by ariebovenberg** [ariebovenberg/whenever#182]
Currently, only the Python version of the library has long, descriptive docstrings. The Rust extension has more brief one-line docstrings. 

IDEs are able to pick up the docstrings from the Python version, but for runtime tools (e.g. jupyter, iPython shell) can't do that of course. Ideally, also the Rust methods would contain the full docstrings. The question is how to do this without outright duplication.

Unfortunately, it's not possible to simply assign the docstrings from Python to Rust (The Rust classes are marked immutable) or vice versa (setting Python docstrings at runtime breaks IDE support)

The current best solution may be to duplicate, but to include a test that flags any desyncs.

**Comment by elenakrittik** [comment]
One option may be to assign docstrings to constants, and then "decorate" rust functions with `#[doc = THIS_FUNC_DOCSTRING]` (rust-analyzer should pick this up just fine), and for python functions make the definition macro accepts constant identifiers instead of string literals

**Comment by ariebovenberg** [comment]
Interesting...you've inspired me to use constants, which can be autogenerated from the Python version. Here is the PR: #188

**Comment by ariebovenberg** [comment]
implemented in the latest release (0.6.14)
