### ISSUE TITLE
More descriptive message on `Ambiguous` and `DoesntExistInZone` exceptions

### ISSUE THREAD

**Issue by ariebovenberg** [ariebovenberg/whenever#26]
When `Ambiguous` and `DoesntExistInZone` exceptions are raised, there is no string indicating the relevant information (time and timezone).

To fix:
- add the information in a readable format. Perhaps with required arguments to the exception constructors.
- ensure the tests check for this string

**Comment by exoriente** [comment]
I'd like to submit a PR for this. Would be fun to contribute and this looks like a good place to start!

**Comment by ariebovenberg** [comment]
This has been released in version 0.3.4, available now 📦
