### ISSUE TITLE
The tests don’t run on Windows yet

### ISSUE THREAD

**Issue by metaperl** [ariebovenberg/whenever#28]
Consider this a placeholder / milestone / reminder ticket.

I too found whenever via the reddit discssion of [the well-written blog post](https://dev.arie.bovenberg.net/blog/python-datetime-pitfalls/).

I was eager to prepare a talk at work about this library but then saw [the tests dont run on Windows](https://whenever.readthedocs.io/en/latest/#contributing).

**Comment by ariebovenberg** [comment]
Yes! Thanks for the reminder. 

In #29, I'm working to at least make the offending tests skip (instead of break) on windows.

**Comment by ariebovenberg** [comment]
@metaperl can you check out the branch `dev-env-improvements` and confirm the tests at least don't break on windows?

**Comment by ariebovenberg** [comment]
I've merged the changes. Let me know if it doesn't work for you.

**Comment by ariebovenberg** [comment]
From [what I've read](https://stackoverflow.com/questions/62004265/python-3-time-tzset-alternative-for-windows), there is no way for Python to set the local timezone in Windows (without affecting the entire system).

Therefore, certain tests will always be skipped on windows. I'll adjust in the readme and close the issue.

**Comment by tibor-reiss** [comment]
I was fiddling around with this for a long time and for windows it seems that the timezone can be set from within python (e.g. calling tzutil, or via this https://stackoverflow.com/questions/20256946/how-to-change-system-timezone-using-python-in-windows). However, the running python process itself will not see the updated timezone. So skip is the best option.

**Comment by ariebovenberg** [comment]
I also got the impression that `tzutil` would set the system timezone _outside_ the Python process too. 

Imagine running the tests as a developer and seeing your system clock go haywire 😂 -- or get stuck on NYC time if the test ever crash 👀
