### ISSUE TITLE
tzdata needed for Windows

### ISSUE THREAD

**Issue by tibor-reiss** [ariebovenberg/whenever#31]
Hello,

under windows, zoneinfo.available_timezones() returns an empty set, thus some tests fail. In linux, more often than not the database is provided.

Proposal: add tzdata as a windows test dependency.

Cheers!

**Comment by ariebovenberg** [comment]
Interesting! Wouldn't this hold for the library itself though too? I'd have to add `tzdata` as a general dependency (for Windows only)

**Comment by tibor-reiss** [comment]
Yeah, practically it's needed, but theoretically it's not mandatory, e.g. if someone only uses LocalDateTime :)

**Comment by ariebovenberg** [comment]
0.3.3 was released with this fix ✅
