### ISSUE TITLE
Consider relaxing Python version constraint

### ISSUE THREAD

**Issue by Fuyukai** [ariebovenberg/whenever#33]
The current version constraint is ``>=3.8.1,<4.0`` which means installing the project in Poetry projects with just a lower bound constraint (such as ``>3.11``) will fail.

Given that Python makes breaking changes in 3.x releases, this cap doesn't really make much sense. (This is a bit of a contentious topic, [ref 1](https://iscinumpy.dev/post/bound-version-constraints/), [ref 2](https://snarky.ca/why-i-dont-like-semver/), and so on).

**Comment by ariebovenberg** [comment]
@Fuyukai looks like a mistake on my side indeed. Should be removed. Would you like to submit the PR?

**Comment by Fuyukai** [comment]
Sent over.

**Comment by ariebovenberg** [comment]
Thanks! New version should be out now.
