### ISSUE TITLE
consider renaming 'naive()' to 'as_naive()'

### ISSUE THREAD

**Issue by bxparks** [ariebovenberg/whenever#61]
A very minor observation, but other conversion functions have the form:

- `as_utc()`
- `as_offset`
- `as_zoned()`
- `as_local()`

But conversion to `NiaveDateTime` is:

- `naive()`

Consider changing this to `as_naive()` for consistency.

**Comment by ariebovenberg** [comment]
I'll admit that a small "note" block is probably not enough to make this clear. Perhaps a diagram like this (hopefully simplified):

<img width="1075" alt="image" src="https://github.com/ariebovenberg/whenever/assets/5999858/ab206172-ed7c-4e59-837f-3994f18ec734">

**Comment by bxparks** [comment]
Ah, I missed the note. The diagram definitely helps.
Though I think of the other "as_xxx()" as "losing information" as well. They do preserve "timestamp()", but they lose other information.

**Comment by ariebovenberg** [comment]
Correct, "losing information" is not the right wording. "loses position on the timeline" is perhaps the best way to describe `naive()` in comparison to methods like `as_zoned()`

**Comment by ariebovenberg** [comment]
I've created a follow-up for visualizing classes and their conversions. This includes rationale for the seemingly inconsistent naming #69.

The current issue is about the specific method, which will not be changed. Closed.
