### ISSUE TITLE
A better tagline

### ISSUE THREAD

**Issue by ariebovenberg** [ariebovenberg/whenever#70]
The tagline for the library needs to be short, descriptive, and enticing.

Some I can think of:
- datetimes made correct and strict
- datetimes defused and modernized
- strict and reliable datetimes
- foolproof datetimes for maintainable code
- datetime without the pitfalls
- datetime reimagined 
- Modern datetime API for Python

Feel free to chime in below 👇

**Comment by JaykeMeijer** [comment]
Time to fuel this discussion a bit.

Some of the suggestions made in private before:
- _datetimes made strict, predictable and typed_
- _datetimes done right_

Some more "opinionated" suggestions - these may be a bit too charged but might serve spice up the discussion:
- _datetime for professionals_
- _datetime for correct code_

From your list I like _datetime without the pitfalls_ or _datetime reimagined_, as it indicates an improvement over the original datetime. However, they do not really convey the "how", only the "what".

**Comment by ariebovenberg** [comment]
> However, they do not really convey the "how", only the "what".

Indeed a tough choice 🤔 . To make things more difficult, it'll soon be rewritten in Rust (_soooo hot right now_ 🔥 ). Then we add "fast" or "written in Rust" to the mix.

Evolutions of previous ideas
- Fast, correct, and typesafe datetimes for Python 
- Datetimes done right, written in Rust
- Correct and typesafe datetimes, written in Rust
- Datetimes made correct and typesafe, written in Rust
- Datetimes redesigned and written in Rust

**Comment by ariebovenberg** [comment]
I've sharpened the selling points of whenever to three aspects:

- DST-safe arithmetic
- typed naive/aware
- fast

which is summarized in the new tagline: "Typed and DST-safe datetimes for Python, written in Rust", or shorter: "Modern datetime library for Python, written in Rust"
